name: Daily Scraper

on:
  schedule:
    - cron: '07 7 * * *'  # Runs at 06:58 UTC (2:58 PM China time)
  workflow_dispatch:      # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager pillow
          pip install undetected-chromedriver
          pip install pytesseract
          
      - name: Run scraper
        run: python scraper.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add today_words.json
          git commit -m "Update words for $(date +'%Y-%m-%d')" || exit 0
          git push
