name: Daily Scraper

on:
  schedule:
    - cron: '30 4 * * *'  # Runs at 04:30 UTC (12:30 PM China time)
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: write  # Required for pushing changes

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git operations
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Chrome and ChromeDriver
        run: |
          # Install Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          
          # Install ChromeDriver using webdriver_manager
          python -m pip install webdriver_manager
          python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install selenium webdriver_manager pillow
          pip install undetected-chromedriver
          pip install pytesseract
          
      - name: Run scraper with logging
        run: |
          echo "Starting scraper..."
          # Create a unique user data directory
          mkdir -p /tmp/chrome-user-data
          export CHROME_USER_DATA_DIR="/tmp/chrome-user-data"
          python scraper.py > scraper_output.log 2>&1
          echo "Scraper completed. Output:"
          cat scraper_output.log
          
      - name: Check if new words were scraped
        run: |
          if [ -s today_words.json ]; then
            echo "New words were scraped successfully"
            cat today_words.json
          else
            echo "ERROR: today_words.json is empty or doesn't exist"
            exit 1
          fi
        
      - name: Commit and push if changed
        run: |
          # Clean up temporary files
          rm -f error_page.html error_state.png google-chrome-stable_current_amd64.deb scraper_output.log
          
          # Configure git
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # Check if today_words.json has changed
          if git diff --quiet today_words.json; then
            echo "No changes to today_words.json"
          else
            echo "Changes detected in today_words.json, committing and pushing..."
            git add today_words.json
            git commit -m "Update words for $(date +'%Y-%m-%d')"
            git push
          fi
